ALTER TABLE PONEY MODIFY ipd INT(9) AUTO_INCREMENT PRIMARY KEY;
ALTER TABLE PONEY AUTO_INCREMENT=131;

ALTER TABLE PERSONNE MODIFY idPersonne INT(9) AUTO_INCREMENT PRIMARY KEY;
ALTER TABLE PERSONNE AUTO_INCREMENT=101;

ALTER TABLE MONITEUR MODIFY idm INT(9) AUTO_INCREMENT PRIMARY KEY;
ALTER TABLE MONITEUR AUTO_INCREMENT=204


ALTER TABLE ELEVE MODIFY ide INT(9) AUTO_INCREMENT PRIMARY KEY;
ALTER TABLE ELEVE AUTO_INCREMENT=1100